frontend/main/routes/main.py
from flask import Blueprint, render_template, make_response, request, current_app, redirect, url_for, flash, session
import json
from . import functions as f

#Crear Blueprint
main = Blueprint('main', __name__, url_prefix='/')


'''
    Este archivo contiene las rutas del frontend.
    - Los metodos DELETE y PUT funcionan solamente en HTML5. Solo funciona en HTTP utilizado en RESTful.
'''

#Ruta principal de los Poetas
@main.route('/poet', methods=['GET', 'POST'])
def index_poet(jwt = None):
    jwt = f.get_jwt()
    if jwt: 
        # Paginacion
        try:
            page = int(request.form.get('n_page'))
        except:
            page = request.form.get("n_page")
            if (page == "< Atras"):
                page = int(f.get_poems_page()) - 1
            elif (page == "Siguiente >"):
                page = int(f.get_poems_page()) + 1
            else:
                page = f.get_poems_page()
                if (page == None):
                    page = 1
                else:
                    page = int(page)
        # Obtengo los poemas de la pagina.
        resp = f.get_poems(jwt=jwt, page=page)
        poems = f.get_json(resp)
        poem_list = poems["poems"]
        # Obtenigo el usuario.
        user = f.get_user(f.get_id())
        user = json.loads(user.text)

        #Redireccionar a función de vista   
        response = make_response(render_template('poet_main_page.html', jwt=jwt, poems = poem_list, user = user, page = int(page)))
        # Seteo la cookie de la pagina.
        response.set_cookie("poems_page", str(page))
        return response
    else:
        #Si no esta logueado, redireccionar a la pagina de login.
        return render_template("view_login.html")


#Ruta Principal de los Usuarios
@main.route('/', methods=['GET', 'POST'])
def index_user():
    # Paginacion
    try:
        page = int(request.form.get('n_page'))
    except:
        page = request.form.get("n_page")
        if (page == "< Atras"):
            page = int(f.get_poems_page()) - 1
        elif (page == "Siguiente >"):
            page = int(f.get_poems_page()) + 1
        else:
            page = f.get_poems_page()
            if (page == None):
                page = 1
            else:
                page = int(page)

    response = f.get_poems(page=page)
    poems = f.get_json(response)
    list_poems = poems["poems"]
    #Redireccionar a función de vista
    response = make_response(render_template('user_main_page.html', poems = list_poems, page = int(page)))
    response.set_cookie("poems_page", str(page))
    return response


#Ruta del Login
@main.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        #Obtener datos del formulario - Esto lo traigo del HTML con los name de los inputs.
        email = request.form.get("email")
        password = request.form.get("password")
        
        if email != "" and password != "":
            response = f.login(email, password)

            if response.ok:
                #Obtener el token desde response.
                response = json.loads(response.text)
                token = response["access_token"]
                user_id = str(response["id"])
                resp = make_response(redirect(url_for('main.index_poet')))
                # Seteo la cookie del token y el id del usuario.
                resp.set_cookie("access_token", token)
                resp.set_cookie("id", user_id)
                return resp

        flash("Your credentials are incorrect!", 'error')
        return render_template("view_login.html", error="Usuario o contraseña incorrectos")
    else:
        return render_template("view_login.html")


#Ruta del Registro
#Registro de un nuevo usuario
@main.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        #Obtener datos del formulario - Esto lo traigo del HTML con los name de los inputs.
        username = request.form.get("username")
        email = request.form.get("email")
        password = request.form.get("password")
        rol = 'poeta'

        if username != "" and email != "" and password != "":
            response = f.register(username, email, password, rol)
            if response.ok:
                flash("Registered user successfully!", "success")
                return redirect(url_for("main.login"))
            else:
                flash("Error registering user!", "error")
                return render_template("view_register.html", error="Error al registrar usuario")
        else:
            flash("Error registering user!", "error")
            return render_template("view_register.html", error="Error al registrar usuario")
    else:
        return render_template("view_register.html")


#Ruta del Logout
#Se deslogea el usuario
@main.route("/logout")
def logout():
    flash("You have successfully logged out!", "success")
    resp = make_response(redirect(url_for("main.login")))
    # Elimino las cookies del token y el id del usuario.
    resp.delete_cookie("access_token")
    resp.delete_cookie("id")
    return resp

frontend/main/routes/poem.py
from flask import Blueprint, render_template, url_for, redirect, json, current_app, request, flash, make_response
import requests
from . import functions as f
from . import auth

#Crear Blueprint
poem = Blueprint('poem', __name__, url_prefix='/poem')


#Ver un poema determinado
@poem.route('/view_user/<int:id>', methods=['GET', 'POST'])
def view_user(id):
    if request.cookies.get('access_token'):
        jwt = f.get_jwt()
        #Verificar si es un str o un int, ya que si hacemos una validacion puede que nos de False.
        user_id = int(f.get_id())
        poem = f.get_poem(id)
        poem = json.loads(poem.text)
        mark = f.get_marks_by_poem_id(id)
        marks = json.loads(mark.text)

        #--- Agregar una Calificacion ---#
        if request.method == 'POST':
            if request.form['comment_method'] == 'COMMENT':                 
                score = request.form['inlineRadioOptions']
                commentary = request.form['commentary']
                user_id = f.get_id()

                if score != "" and commentary != "":
                    response = f.add_mark(user_id=user_id, poem_id=id, score=score, commentary=commentary)
                    if response.ok:
                        flash('Mark added successfully', 'success')
                        return make_response(redirect(url_for('poem.view_user', id=id)))
                    else:
                        flash('Error adding mark', 'error')
                        return render_template('view_poem_user.html', poem = poem, marks = marks, jwt=f.get_jwt())
                else:
                    return redirect(url_for('poem.my_poems'))
        
        #--- Eliminar un Poema ---#
            if request.form['delete_method'] == 'DELETE':
                response = f.delete_poem(id, jwt=jwt)
                if response.ok:
                    flash('Poem deleted successfully', 'success')
                    return redirect(url_for('poem.my_poems'))
                else:
                    flash('Error deleting poem', 'error')
                    return redirect(url_for('poem.my_poems'))  

        #Mostrar template
        response = make_response(render_template('view_poem_poet.html', jwt = jwt, poem = poem, marks = marks, user_id = user_id, page=f.get_poems_page()))
        response.set_cookie("poems_page", str(1))
        return response

    else:
        poem = f.get_poem(id)
        poem = json.loads(poem.text)
        mark = f.get_marks_by_poem_id(id)
        marks = json.loads(mark.text)
        #Mostrar template
        response = make_response(render_template('view_poem_user.html', poem = poem, marks = marks, jwt=None, page=f.get_poems_page()))
        response.set_cookie("poems_page", str(1))
        return response

#Ver mi lista de poemas
@poem.route('/my_poems')
def my_poems():
    jwt = f.get_jwt()
    if jwt:
        user = auth.load_user(jwt)
        resp = f.get_poems_by_id(user["id"], perpage=10)
        poems = json.loads(resp.text)
        poemsList = poems["poems"]
        response = make_response(render_template('view_poet_mypoems.html', jwt=jwt, poems = poemsList, page=f.get_poems_page()))
        response.set_cookie("poems_page", str(1))
        return response
    else:
        return redirect(url_for('main.login'))


#Ver lista de poemas calificados de un poeta en particular
@poem.route('/my_ratings')
def my_ratings():
    jwt = f.get_jwt()
    if jwt:
        user = auth.load_user(jwt)
        user_id = str(user["id"])
        resp = f.get_marks_by_poet_id(user_id)
        marks = json.loads(resp.text)
        response = make_response(render_template('view_poet_myratings.html', jwt=jwt, marks = marks, page=f.get_poems_page()))
        response.set_cookie("poems_page", str(1))
        return response
    else:
        return redirect(url_for('main.login'))


#Crear un poema nuevo
@poem.route('/create', methods=['GET', 'POST'])
def create():
    jwt = f.get_jwt()
    if jwt:
        if request.method == 'POST':
            title = request.form['title']
            body = request.form['body']
            print(title)
            print(body)
            id = f.get_id()
            print(id)
            data = {"user_id": id, "title": title, "body": body}
            headers = f.get_headers(without_token=False)
            
            if title != "" and body != "":
                response = requests.post(f'{current_app.config["API_URL"]}/poems', json=data, headers=headers)
                print(response)
                if response.ok:
                    flash('Poem added successfully', 'success')
                    response = f.json_load(response)
                    return redirect(url_for('poem.view_user', id=response["id"], jwt=jwt))
                else:
                    flash('Error adding poem', 'error')
                    return redirect(url_for('poem.create'))
            else:
                flash('Error adding poem', 'error')
                return redirect(url_for('poem.create'))
        else:
            #Mostrar template
            return render_template('view_add_poem.html', jwt=f.get_jwt())
    else:
        return redirect(url_for('main.login'))


#Editar un poema
@poem.route('/edit_poem/<int:id>', methods=['GET', 'POST'])
def edit_poem(id):
    jwt = f.get_jwt()
    if jwt:
        if request.method == 'POST':
            title = request.form['title']
            body = request.form['body']
            if title != "" and body != "":
                response = f.edit_poem(id=id, title=title, body=body)
                if response.ok:
                    flash('Poem edited successfully', 'success')
                    return make_response(redirect(url_for('poem.view_user', id=id)))
                else:
                    flash('Error editing poem', 'error')
                    poem = f.get_poem(id)
                    poem = json.loads(poem.text)
                    return render_template('view_edit_poem.html', jwt = jwt, poem = poem)
            else:
                return redirect(url_for('poem.my_poems'))
        else:
            poem = f.get_poem(id)
            poem = f.json_load(poem)
            return render_template('view_edit_poem.html', jwt = jwt, poem = poem)
    else:
        return redirect(url_for('main.login'))

##

frontend/main/routes/user.py
from flask import Blueprint, render_template, json, request, redirect, url_for, flash, make_response, current_app
from . import functions as f
from . import auth

#Crear Blueprint
user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/details')
def details():
    jwt = f.get_jwt()
    if jwt:
        user = auth.load_user(jwt)
        # Guardamos la información de usuario en una variable.
        user_info = f.get_user_info(user["id"])
        user_info = json.loads(user_info.text)

        return render_template('view_poet_credentials.html', jwt = jwt, user_info = user_info)
    else:
        return redirect(url_for('main.login'))


#Borrar cuenta de usuario
@user.route('/delete')
def delete():
    jwt = f.get_jwt()
    if jwt:
        user_info = auth.load_user(jwt)
        user_id = str(user_info["id"])
        return render_template('view_poet_delete.html', jwt = jwt, user_id = user_id)
    else:
        return redirect(url_for('main.login'))

@user.route('/delete_account/<int:id>')
def delete_account(id):
    jwt = f.get_jwt()
    if jwt:
        #Borrar cuenta
        response = f.delete_user(id)
        if response.ok:
            flash("Account successfully deleted", "success")
            return redirect(url_for('main.login'))
        else:
            flash("Failed to delete account", "error")
            return redirect(url_for('main.login'))

#Editar cuenta de usuario
@user.route('/edit_profile', methods=['GET', 'POST'])
def edit_credentials():
    jwt = f.get_jwt()
    if jwt:
        if request.method == 'POST':
            name = request.form['name']
            email = request.form['email']
            password = request.form['password']
            user_info = auth.load_user(jwt)
            user_id = str(user_info["id"])
            print(user_id)
            if name != "" and email != "" and password != "":
                response = f.edit_user(user_id, name, email, password)
                if response.ok:
                    flash("Account successfully edited", "success")
                    return make_response(redirect(url_for('user.details')))
                else:
                    flash("Failed to edit account", "error")
                    return redirect(url_for('user.details'))
            else:
                return redirect(url_for('user.details'))
        else:
            return render_template('view_edit_profile.html', jwt = jwt)
    else:
        return redirect(url_for('main.login'))

frontend/main/templates/base.html
<!DOCTYPE html>
<html lang="ar">
    <head>
        {% block menu %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.rtl.min.css" integrity="sha384-dc2NSrAXbAkjrdm9IYrX10fQq9SDG6Vjz7nQVKdKcJl3pC+k37e7qJR5MVSCS+wR" crossorigin="anonymous"> 
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <title>the poetizer / Poets Place</title>
	  <head>
        {% block content_menu %}{% endblock %}
        {% endblock %}

        <!-- Dentro de HTML puedo usar funciones de Flask, como es hacer una request para saber
        si el usuario esta logeado o no, y mostrar el navbar correspondiente. -->

    {% if jwt %}
    <!-- ===================================================== -->
      <!-- HOME-->
      <!-- NAVBAR POETAS -->
      <div class="home-header">
        <nav class="navbar navbar-expand-lg">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">the poetizer</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('main.index_poet')}}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for('poem.my_poems')}}">My Poems</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for('poem.my_ratings')}}">My Ratings</a>
                  </li>
                  <div class="dropdown text-end">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                      <img src="{{url_for('static', filename='img/avatar.png')}}" alt="mdo" width="32" height="32" class="rounded-circle">
                    </a>
                  <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                      <li><a class="dropdown-item" href="{{url_for('user.details')}}">USER DETAILS</a></li>
                      <li><a class="dropdown-item" href="{{url_for('user.edit_credentials')}}">EDIT CREDENTIALS</a></li>
                      <li><a class="dropdown-item text-danger" href="{{url_for('user.delete')}}">DELETE ACCOUNT</a></li>
                      <li>            
                        <div class="darkmode">
                        <input type="checkbox" class="checkbox" id="chk" onclick="darkmode()"/>
                        <label class="label" for="chk">
                          <i class="fas fa-moon"></i>
                          <i class="fas fa-sun"></i>
                          <div class="ball"></div>
                        </label>
                        </div>
                      </li>
                      <li><a class="dropdown-item text-danger" href="{{url_for('main.logout')}}">Sign out</a></li>
                  </ul>
                  </div>
                  </ul>
                  </div>
                </div>
                </nav>
              </div>
              </ul>
              </div>
          </div>
        </nav>
    </div>
    <!-- ===================================================== -->

    {% else %}
    <!-- ===================================================== -->
    <!-- HOME-->
    <!-- NAVBAR USUARIOS COMUNES -->
    <div class="home-header">
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">the poetizer</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                </li>
                <div>
                  <form class="d-flex justify-content-center" role="go-home">
                    <a class="btn btn-primary btn-primary-outline-success" id="btn-register" type="button" href="{{url_for('main.register')}}">REGISTER</a>
                    <a class="btn btn-primary-outline-success" id="btn-login" type="button" href="{{url_for('main.login')}}">LOGIN</a>
                      <div class="darkmode">
                        <div class="darkmode">
                          <input type="checkbox" class="checkbox" id="chk" onclick="darkmode()"/>
                          <label class="label" for="chk">
                            <i class="fas fa-moon"></i>
                            <i class="fas fa-sun"></i>
                            <div class="ball"></div>
                          </label>
                        </div>
                      </div>
                  </form>
                </div>
            </ul>
            </div>
        </div>
      </nav>
    </div>
    <div class="ad container-fluid justify-content-center">
      <div class="welcome-ad">
          <p>👋 HELLO</p>
      </div>
      <div class="text-ad">
          <p>REGISTER ON OUR PAGE TO SHARE YOUR ART, POET!</p>
      </div>
    </div>
    <!-- ===================================================== -->
    {% endif %}

        {% block content %}
        {% with messages = get_flashed_messages(with_categories=true) %}
                {% for category, message in messages %}
                    <div class="alert-{{category}}">{{ message }}</div>
                {% endfor %}
        {% endwith %}
        {% endblock %}
        <!-- ===================================================== -->
        <!-- FOOTER -->
        <div class="footer container-fluid">
          <div class="row">
            <p>Copyright 2022 - the poetizer</p>
          </div>
        </div>
        <!-- ===================================================== -->
        <!-- Option 1: Bootstrap Bundle with Popper -->
        <div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        <script src="{{url_for('static', filename='js/dark_mode.js')}}"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        </div>
      </body>
</html>

frontend/main/templates/user_main_page.html
{% extends 'base.html' %}
  {% block menu %}
  {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/user_main_page_styles.css')}}">
  {% endblock %}    
  {% block content_menu %}
    <header>
    <!-- Agrego algunos estilos para que funcionen bien las imagenes con el darkmode -->
    <style>
      body
      {
        background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url("{{url_for('static', filename='img/arte2.jpg')}}");
        background-repeat: no-repeat;
        background-size: 100% 30%;
      }
      body.dark 
      {
        background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url("{{url_for('static', filename='img/arte2.jpg')}}");
	      background-color: #292C35;

      }
    </style>
    <!-- Agrego algunos estilos para que funcionen bien las imagenes con el darkmode -->
      <nav class="navbar navbar-expand-lg bg-transparent p-2" id="menu">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <span class="text-white fs-1 fw-bold">
              the poetizer
            </span> 
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('main.index_user')}}">Home</a>
              </li>

            <!-- TODO: agregar lista EN-ES, que se pueda elegir el idioma de la pagina, por defecto EN
              <li class="nav-item">
                <a class="nav-link" href="#">Languaje</a>
              </li>
            </ul>
            
            <!-- TODO: cambiar el boton por uno de icono que se despliegue -->
            <!-- <form class="form-inline d-flex justify-content-center md-form form-sm mt-0">
              <input class="form-control form-control-sm ml-3 w-75" type="text" placeholder="Search"
                aria-label="Search">
            </form> -->
          </div>
        </div>
      </nav>
      <div class="container d-flex justify-content-center" id="phrase-txt">
        <p>"La poesía no quiere adeptos, quiere amantes"</p>
      </div>
        <div class="visitor-menu justify-content-center">
          <form class="d-flex justify-content-center" role="go-home" id="btn-login">
              <a class="btn btn-primary btn-primary-outline-success" type="button" href="{{url_for('main.login')}}">LOGIN</a>
          </form>
          <div class="divide-line d-flex container justify-content-center">
              <hr>
          </div>
          <form class="d-flex justify-content-center" role="go-home" id="btn-visitor">
              <a class="btn btn-outline-secondary btn-primary-outline-success" type="button" data-toggle="button" aria-pressed="false" autocomplete="off">VISITOR</a>
          </form>
        </div>
        <div class="container d-flex justify-content-center" id="tf-txt">
          <p>tp</p>
        </div>
    </header>
    <!-- ===================================================== -->
    {% endblock%}

    {% block btn %}
    <a class="nav-link active" aria-current="page" href="{{url_for('main.index_user')}}">Home</a>
    {% endblock %}

    {% block content_navbar %}
    <!-- ===================================================== -->
    <!-- HOME-->
    <!-- NAVBAR HOME -->
                <form class="d-flex justify-content-center" role="go-home" id="btn-login">
                    <a class="btn btn-primary btn-primary-outline-success" type="button" href="{{url_for('main.login')}}">LOGIN</a>
                </form>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="ad container-fluid justify-content-center">
        <div class="welcome-ad">
            <p>👋 HELLO</p>
        </div>
        <div class="text-ad">
          <p>REGISTER ON OUR PAGE TO SHARE YOUR ART, POET!</p>
        </div>
    </div>
    <!-- ===================================================== -->
    {% endblock %}
    
    {% block content %}
    {{ super() }}
    <!-- ===================================================== -->
  <form method="POST" action="{{url_for('main.index_user')}}">
        <!-- ===================================================== -->
    <!-- POEMS CARDS -->
    <div>
      <h1 class="poems-card-text">POEMS LIST</h1>
    </div>
    <!-- ===================================================== -->
    <!-- FILTERS -->
    <div class="row section-1">
      <!--Columna -->
      <div class="col-md-12 ">
        <div id="filterbar">
          <select class="poems-filter">
              <option value="">Filter by DATE</option>
              <option value="">Filter by TITLE</option>
              <option value="selected">Filter by RATING</option>
          </select>
        </div>
      </div><!--Fin de la columna -->
     </div><!--Fin de la fila -->
    <!-- ===================================================== -->

    <!-- ===================================================== -->
    <tbody>
      {% for poem in poems %}
      <!-- CARD 1 -->
      <div class="card container d-flex justify-content-center">
        <div class="img-card">
          <img src="{{url_for('static', filename='img/poem.jpeg')}}" class="card-img-top" alt="...">
        </div>
        <div class="content">
          <div class="poem-title">
            <h3>{{poem.title}}</h3>
            <span>{{poem.user.name}}</span>
          </div>
          <div class="poem-text">
            <p>{{poem.body}}</p>
          </div>
          <div class="btn-container">
            <a type="btn btn-primary btn-primary-outline-success" href="{{url_for('poem.view_user',id=poem.id)}}">View All</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </tbody>
    <!-- ===================================================== -->
    <!-- ===================================================== -->
      <!-- PAGINATION -->
      <div class="paginate">    
        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center">
            <li class="page-item"><input type="submit" class="page-link" name="n_page" value="< Atras" {% if page == 1 %} hidden {% endif %}></li>
            
            {% if page < 3 %}
            <li class="page-item"><input type="submit" class="page-link" name="n_page" value="1"/></li>
            <li class="page-item"><input type="submit" class="page-link" name="n_page" value="2"/></li>
            <li class="page-item"><input type="submit" class="page-link" name="n_page" value="3"/></li>
            {% else %}
            <li class="page-item"><input type="submit" class="page-link" name="n_page" value="{{page - 2}}"/></li>
            <li class="page-item"><input type="submit" class="page-link" name="n_page" value="{{page - 1}}"/></li>
            <li class="page-item"><input type="submit" class="page-link" name="n_page" value="{{page}}"/></li>
            <li class="page-item"><input type="submit" class="page-link" name="n_page" value="{{page + 1}}"/></li>
            <li class="page-item"><input type="submit" class="page-link" name="n_page" value="{{page + 2}}"/></li>
            {% endif %}
            
            <li class="page-item"><input type="submit" class="page-link" name="n_page" value="Siguiente >"/></li>
            </ul>
        </nav>
      </div>
  </form>
    <!-- ===================================================== -->
    {% endblock %}

frontend/main/templates/view_edit_poem.html
{% extends 'base.html' %}
{% block menu %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/view_add_poem.css')}}">
{% endblock %}

{% block content_menu %}
    <!-- Agrego algunos estilos para que funcionen bien las imagenes con el darkmode -->
    <style>
        body.dark 
        {
            background-color: #292C35;
        }
    </style>
    <!-- Agrego algunos estilos para que funcionen bien las imagenes con el darkmode -->
{% endblock %}

{% block content %}
{{ super() }}

        <!-- ===================================================== -->
        <!-- VIEW ALL POEM INFO -->
        <!-- POEM -->
        <div class="row">
            <!-- Espacio en blanco -->
            <div class="col-lg-2 col-md-1"></div>
            <div class="col-lg-8 col-md-10 principal-container">
                <div class="row">
                    <!--POEM -->
                    <form method="POST" id="edit_poem_form" action="{{url_for('poem.edit_poem', id=poem.id)}}">
                        <div class="card">
                            <div class="poem-title">
                                <div class="poemtitle">
                                    <input class="form-control" type="poemtitle" name="title" placeholder="POEM TITLE..">
                                </div>
                                <div class="poembody">
                                    <textarea class="form-control" name="body" rows="3" placeholder="INSERT YOUR POEM HERE.."></textarea>
                                </div>
                            </div>
                        </div>
                        <div id="btn-post">
                            <button class="btn btn-primary btn-primary-outline-success" type="submit">POST</button>
                        </div>
                        <div class="btn-back">
                            <a type="button" class="btn btn-outline-secondary" href="{{url_for('main.index_poet')}}">Back Home</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-2 col-md-1"></div>
        </div>
{% endblock %}